# -*- coding: utf-8 -*-
d = {
"கண்டுபுடி": "AutoFind",
"அஞ்சல்": "Anjal",
"பாமினி": "Bamini",	
"பூமி": "Boomi ",
"டியாச்ரிடிக்": "Diacritic",
"தினகரன்": "Dinakaran",
"தினமணி": "Dinamani",
"தினத்தந்தி": "Dinathanthy",
"இன்டோவெப்": "Indoweb",
"கவிபிரியா": "Kavipriya",
"கோயல்என்": "Koeln",
"லிபி"	: "Libi",
"முரசொலி": "Murasoli",
"மலை": "Mylai",
"நக்கீரன்": "Nakkeeran",
"பழைய விகடன்": "Old Vikatan",
"பல்லவர்": "Pallavar",
"ரோமன்": "Roman",
"ஸ்ரீலிபி": "Shreelipi",
"சாஃப்ட் வியூ": "Softview",
"டேப்": "Tab",
"டேஸ்"	: "Tace",
"டாம்": "Tam",
"டிஸ்கி": "Tscii",
"வானவில்"	: "Vanavil",
"வெப்உலகம்": "Webulagam"
}